image: eicweb.phy.anl.gov:4567/eic/juggler/juggler:latest

generate:
  stage: test
  script:
    - test "$(scripts/generate.sh)" = "e-_1GeV_45to135deg.steer"
    - scripts/generate.sh && test -f e-_1GeV_45to135deg.steer
    - scripts/generate.sh e- 1*GeV 45 135 && test -f e-_1GeV_45to135deg.steer
    - scripts/generate.sh J/psi 1*GeV && test -f Jpsi_1GeV_45to135deg.steer
    - scripts/generate.sh eta_prime 1*GeV && test -f etaprime_1GeV_45to135deg.steer
    - scripts/generate.sh anti_nu_mu 1*GeV && test -f antinumu_1GeV_45to135deg.steer

run_electron_1GeV_45to135deg:
  stage: test
  script:
    - scripts/run.sh $(scripts/generate.sh e- 1*GeV 45 135) 100 && test -f RECO/SINGLE/e-/1GeV/45to135deg/e-_1GeV_45to135deg.root

run_pion_1GeV_3to50deg_0001:
  stage: test
  script:
    - scripts/run.sh $(scripts/generate.sh pi+ 1*GeV 3 50) 100 1 && test -f RECO/SINGLE/pi+/1GeV/3to50deg/pi+_1GeV_3to50deg.0001.root
