image: eicweb.phy.anl.gov:4567/eic/juggler/juggler:latest

stages:
  - config
  - test
  - deploy

generate:
  stage: config
  script:
    - test "$(scripts/generate.sh)" = "e-_1GeV_45to135deg.steer"
    - scripts/generate.sh && test -f e-_1GeV_45to135deg.steer
    - scripts/generate.sh e- 1*GeV 45 135 && test -f e-_1GeV_45to135deg.steer
    - scripts/generate.sh J/psi 1*GeV && test -f Jpsi_1GeV_45to135deg.steer
    - scripts/generate.sh eta_prime 1*GeV && test -f etaprime_1GeV_45to135deg.steer
    - scripts/generate.sh anti_nu_mu 1*GeV && test -f antinumu_1GeV_45to135deg.steer

.test:
  stage: test
  parallel:
    matrix:
      - TAG:
        - "testing"
        - "4.0-acadia-stable"
        - "4.0-canyonlands-stable"
  image: eicweb.phy.anl.gov:4567/containers/eic_container/jug_xl:${TAG}

run_electron_1GeV_45to135deg:
  extends: .test
  script:
    - scripts/generate.sh e- 1*GeV 45 135
    - mkdir -p EVGEN/CI/SINGLE/e-/1GeV/45to135deg
    - cp e-_1GeV_45to135deg.steer EVGEN/CI/SINGLE/e-/1GeV/45to135deg/e-_1GeV_45to135deg.steer
    - COPYRECO=true scripts/run.sh EVGEN/CI/SINGLE/e-/1GeV/45to135deg/e-_1GeV_45to135deg.steer 100
    - test -f RECO/*/CI/SINGLE/e-/1GeV/45to135deg/e-_1GeV_45to135deg.root

run_pion_1GeV_3to50deg_0001:
  extends: .test
  script:
    - scripts/generate.sh pi+ 1*GeV 3 50
    - mkdir -p EVGEN/CI/SINGLE/pi+/1GeV/3to50deg
    - cp pi+_1GeV_3to50deg.steer EVGEN/CI/SINGLE/pi+/1GeV/3to50deg/pi+_1GeV_3to50deg.steer
    - COPYRECO=true scripts/run.sh EVGEN/CI/SINGLE/pi+/1GeV/3to50deg/pi+_1GeV_3to50deg.steer 100 1
    - test -f RECO/*/CI/SINGLE/pi+/1GeV/3to50deg/pi+_1GeV_3to50deg.0001.root

jug_xl:master:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_SERVER_HOST == "eicweb.phy.anl.gov"'
      when: on_success
    - when: never
  needs:
    - run_electron_1GeV_45to135deg
    - run_pion_1GeV_3to50deg_0001
  trigger:
    project: containers/eic_container
  allow_failure: true
