name: Build against eic-shell

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        setup: /opt/detector/setup.sh
        run: |
          test "$(scripts/generate.sh)" = "e-_1GeV_45to135deg.steer"
          scripts/generate.sh && test -f e-_1GeV_45to135deg.steer
          scripts/generate.sh e- 1*GeV 45 135 && test -f e-_1GeV_45to135deg.steer
          scripts/generate.sh J/psi 1*GeV && test -f Jpsi_1GeV_45to135deg.steer
          scripts/generate.sh eta_prime 1*GeV && test -f etaprime_1GeV_45to135deg.steer
          scripts/generate.sh anti_nu_mu 1*GeV && test -f antinumu_1GeV_45to135deg.steer

  run_electron_1GeV_45to135deg:
    needs: generate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        setup: /opt/detector/setup.sh
        run: |
          COPYRECO=true scripts/run.sh EVGEN/SINGLE/e-/1GeV/45to135deg/e-_1GeV_45to135deg.steer 100
          test -f RECO/*/*/SINGLE/e-/1GeV/45to135deg/e-_1GeV_45to135deg.eicrecon.tree.edm4eic.root

  run_pion_1GeV_3to50deg_0001:
    needs: generate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        platform-release: "jug_xl:nightly"
        setup: /opt/detector/setup.sh
        run: |
          COPYRECO=true scripts/run.sh EVGEN/SINGLE/pi+/1GeV/3to50deg/pi+_1GeV_3to50deg.steer 100 0001
          test -f RECO/*/*/SINGLE/pi+/1GeV/3to50deg/pi+_1GeV_3to50deg.0001.eicrecon.tree.edm4eic.root
